/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplications;

import dao.UsuarioDao;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.Usuario;

/**
 *
 * @author Penna
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    public FrameLogin() {
        initComponents();
        redimensionarImagem();
    }
    private void redimensionarImagem() {
       // Carregar a imagem original
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/1722.jpg"));
        
        // Redimensionar a imagem para caber no JPanel (jPanel2)
         Image img = icon.getImage().getScaledInstance(jLabelImagem.getWidth(), jLabelImagem.getHeight(), Image.SCALE_SMOOTH);
        
        // Definir a imagem redimensionada no JLabel
        jLabelImagem.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFEmailLogin = new javax.swing.JTextField();
        jTFSenhaLogin = new javax.swing.JTextField();
        jBtnLogar = new javax.swing.JButton();
        jBtnVoltar = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMAIL");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, 50));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SENHA");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 70));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 200, 50));
        getContentPane().add(jTFEmailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 500, 50));
        getContentPane().add(jTFSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 500, 50));

        jBtnLogar.setBackground(new java.awt.Color(102, 255, 102));
        jBtnLogar.setText("LOGAR");
        jBtnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 233, 65));

        jBtnVoltar.setBackground(new java.awt.Color(204, 204, 204));
        jBtnVoltar.setText("VOLTAR");
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 233, 65));

        jLabelImagem.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogarActionPerformed
       
        //VERIFICAR SE TODOS OS CAMPOS FORAM PREENCHIDOS
        if(!jTFEmailLogin.getText().isEmpty() && !jTFSenhaLogin.getText().isEmpty()){
          UsuarioDao usuarioDao = new UsuarioDao();
          //CRIAR NOVO OBJETO USUARIO 
          Usuario usuario = new Usuario(jTFEmailLogin.getText(),jTFSenhaLogin.getText());
          
          if(!usuarioDao.autenticarUsuario(jTFEmailLogin.getText(), jTFSenhaLogin.getText())){
              JOptionPane.showMessageDialog(null, "Usuario ainda não está cadastrado!","ERRO",JOptionPane.ERROR_MESSAGE);
          }else{
              //PEGAR O ID DELE
              usuarioDao.obterId(usuario);
              //SE FOR ADM...
              if(jTFEmailLogin.getText().equals("admin") &&  jTFSenhaLogin.getText().equals("admin")){
              FrameMenuBibliotecaAdmin f = new FrameMenuBibliotecaAdmin(usuario);
              f.setVisible(true);
              this.dispose();
              }else{
              FrameMenuBiblioteca f = new FrameMenuBiblioteca(usuario);
              f.setVisible(true);
              this.dispose();
              }
          }
       }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!","ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnLogarActionPerformed

    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        FrameLoginCadastrar f = new FrameLoginCadastrar();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogar;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JTextField jTFEmailLogin;
    private javax.swing.JTextField jTFSenhaLogin;
    // End of variables declaration//GEN-END:variables
}
